import psycopg2
from .db_setup import get_db_connection
from pathlib import Path
import sys
import os

current_dir = Path(__file__).resolve().parent 
project_root = current_dir.parent 
sys.path.append(str(project_root))

import QR.qr_generator as qr_generator
from face_auth.recognizer import FaceRecognizer

def add_employee(first_name, last_name, photo_path): 
    """
    1. Generates face vector features.
    2. Inserts employee into 'employees' and retrieves the new ID.
    3. Inserts the first entry into 'verification_logs'.
    4. Generates a QR code.
    """
    recognizer = FaceRecognizer()
    
    # --- 1. FACE FEATURE GENERATION ---
    print(f"Loading image from: {photo_path}")
    image = recognizer.load_image_file(photo_path)
    if image is None:
        print(f"Error: Could not load image from path: {photo_path}")
        return None
        
    vector_features = recognizer.get_face_encoding(image)
    if vector_features is None:
        print("Error: Could not extract face features.")
        return None
        
    if hasattr(vector_features, 'tolist'):
        vector_features = vector_features.tolist()
        
    # --- 2. DATABASE OPERATIONS ---
    qr_hash = qr_generator.generate_unique_qr_hash()
    qr_expiration_date = qr_generator.create_qr_expiration_date()
    print(f"Generated QR Hash: {qr_hash}")
    print(f"Generated QR Expiration Date: {qr_expiration_date}")
    
    conn = get_db_connection()
    if not conn:
        return None

    cur = conn.cursor()
    try:
        # STEP A: Insert employee first and RETRIEVE their ID
        cur.execute("""
            INSERT INTO employees (first_name, last_name, qr_hash, vector_features, photo_path, qr_expiration_date)
            VALUES (%s, %s, %s, %s, %s, %s)
            RETURNING id;
        """, (first_name, last_name, qr_hash, vector_features, photo_path, qr_expiration_date))

        # Retrieve the ID generated by PostgreSQL
        employee_id = cur.fetchone()[0]

        # STEP B: Add log using the correct employee_id
        # Ensure the table is named 'verification_logs' with columns: employee_id, status, reason
        cur.execute("""
            INSERT INTO verification_logs (employee_id, status, reason)
            VALUES (%s, %s, %s);
        """, (employee_id, False, "New employee registration"))

        conn.commit()
        print(f"Employee inserted with ID: {employee_id}")

        # --- 3. QR CODE GENERATION ---
        filename_prefix = f"qr_{first_name}_{last_name}"
        qr_file_path = qr_generator.create_qr_image(qr_hash, filename_prefix)
        
        if qr_file_path:
            print(f"QR Code generated: {qr_file_path}")
        
        return employee_id

    except Exception as e:
        conn.rollback()
        print("Insert error:", e)
        return None
    finally:
        cur.close()
        conn.close()

def get_employee_id_by_qr(qr_hash):
    """Retrieves the employee ID based on their unique QR hash."""
    conn = get_db_connection()
    if not conn:
        return None

    cur = conn.cursor()
    employee_id = None
    try:
        cur.execute("""
            SELECT id
            FROM employees
            WHERE qr_hash = %s;
        """, (qr_hash,))

        result = cur.fetchone()
        employee_id = result[0] if result else None

    except Exception as e:
        print("ID query error:", e)
    finally:
        if conn:
            cur.close()
            conn.close()
        return employee_id
    
def get_employee_by_qr(qr_hash):
    """
    Fetches the employee data by QR hash.
    Returns a dictionary with keys: id, first_name, vector_features, photo_path, or None if not found.
    """
    conn = get_db_connection()
    if not conn:
        return None
    
    try:
        cur = conn.cursor()
        cur.execute(
            "SELECT id, first_name, vector_features, photo_path, qr_expiration_date, last_name FROM employees WHERE qr_hash = %s",
            (qr_hash,)
        )
        result = cur.fetchone()
        if result:
            return {
                "id": result[0],
                "first_name": result[1],
                "vector_features": result[2],
                "photo_path": result[3],
                "qr_expiration_date": result[4],
                "qr_hash": qr_hash,
                "qr_path": f"generated_qrs/qr_{result[1]}_{result[5]}.png"
            }
        return None
    except Exception as e:
        print(f"Error fetching employee by QR: {e}")
        return None
    finally:
        conn.close()

def update_expiry_by_qr_hash(qr_hash, new_expiry_date):
    """Updates the QR expiration date for a specific employee."""
    conn = get_db_connection()
    if not conn:
        return False

    cur = conn.cursor()
    try:
        cur.execute("""
            UPDATE employees
            SET qr_expiration_date = %s
            WHERE qr_hash = %s;
        """, (new_expiry_date, qr_hash))

        conn.commit()
        return True
    except Exception as e:
        print("Update error:", e)
        conn.rollback()
        return False
    finally:
        if cur:
            cur.close()
        if conn:
            conn.close()

def delete_employee(employee_id):
    """Deletes an employee record by their ID (internal use)."""
    conn = get_db_connection()
    if not conn:
        return

    cur = conn.cursor()
    try:
        cur.execute("""
            DELETE FROM employees
            WHERE id = %s;
        """, (employee_id,))

        conn.commit()
        print(f"Employee {employee_id} removed.")

    except Exception as e:
        conn.rollback()
        print("Delete error:", e)
    finally:
        cur.close()
        conn.close()


def delete_employee_by_qr_hash(qr_hash):
    """Deletes an employee based on their QR hash."""
    employee_id = get_employee_id_by_qr(qr_hash)

    if employee_id is None:
        print(f"Deletion: Employee with QR hash {qr_hash} does not exist.")
        return False
    
    delete_employee(employee_id)
    log_verification_event(qr_hash, False, "Employee deleted")
    return True

def log_verification_event(qr_hash, status, reason="No data provided"):
    """Adds a new entry to the logs history for the employee with the given QR."""
    employee_id = get_employee_id_by_qr(qr_hash)
    
    if employee_id is None:
        print(f"Error: Employee not found for QR: {qr_hash}")
        return None

    conn = get_db_connection()
    if not conn: return None
    cur = conn.cursor()
    
    try:
        cur.execute("""
            INSERT INTO verification_logs (employee_id, status, reason)
            VALUES (%s, %s, %s)
            RETURNING event_time;
        """, (employee_id, status, reason))
        
        timestamp = cur.fetchone()[0]
        conn.commit()
        print(f"Logged: ID {employee_id}, Status: {status}, Time: {timestamp}")
        return True
    except Exception as e:
        conn.rollback()
        print(f"Logging error: {e}")
        return False
    finally:
        cur.close()
        conn.close()

def get_latest_status(employee_id):
    """
    Fetches employee data along with their latest log and displays it
    in a readable, formatted line.
    """
    conn = get_db_connection()
    if not conn:
        print("Error: No database connection.")
        return None
        
    cur = conn.cursor()
    try:
        # Using LEFT JOIN to fetch data even if there are no logs yet
        cur.execute("""
            SELECT 
                e.first_name, 
                e.last_name, 
                v.status, 
                v.event_time, 
                v.reason 
            FROM employees e
            LEFT JOIN verification_logs v ON e.id = v.employee_id
            WHERE e.id = %s 
            ORDER BY v.event_time DESC NULLS LAST, v.id DESC NULLS LAST
            LIMIT 1;
        """, (employee_id,))
        
        result = cur.fetchone()
        
        if result:
            # Unpack data from the tuple
            first_name, last_name, status, event_time, reason = result
            
            # 1. Format Name and Surname (e.g., John SMITH)
            display_name = f"{first_name.capitalize()} {last_name.upper()}"
            
            # 2. Format Status (icon + text)
            status_display = "VERIFIED" if status else "ACCESS DENIED"
            
            # 3. Format Time (HH:MM:SS DD.MM.YYYY)
            time_display = event_time.strftime("%H:%M:%S %d.%m.%Y") if event_time else "NO LOGS"
            
            # 4. Format Reason
            reason_display = reason if reason else "No information"

            # DISPLAY IN A SINGLE LINE
            print(f"ID: {employee_id} | {display_name} | STATUS: {status_display} | TIME: {time_display} | REASON: {reason_display}")
            
            return result
        else:
            print(f"Error: Employee with ID {employee_id} not found.")
            return None

    except Exception as e:
        print(f"Error fetching status: {e}")
        return None
    finally:
        cur.close()
        conn.close()

def get_logs(employee_id):
    """
    Fetches all logs for a given employee ID and displays them
    as a formatted list.
    """
    conn = get_db_connection()
    if not conn:
        print("Error: No database connection.")
        return None
        
    cur = conn.cursor()
    try:
        # 1. REMOVED 'LIMIT 1' to get all records
        cur.execute("""
            SELECT 
                e.first_name, 
                e.last_name, 
                v.status, 
                v.event_time, 
                v.reason 
            FROM employees e
            LEFT JOIN verification_logs v ON e.id = v.employee_id
            WHERE e.id = %s 
            ORDER BY v.event_time DESC NULLS LAST, v.id DESC NULLS LAST;
        """, (employee_id,))
        
        # 2. CHANGED to fetchall() to get a list of results
        results = cur.fetchall()
        
        if results:
            print(f"--- LOG HISTORY FOR ID: {employee_id} ---")
            
            # 3. LOOP through all records
            for row in results:
                first_name, last_name, status, event_time, reason = row
                
                display_name = f"{first_name.capitalize()} {last_name.upper()}"
                status_display = "VERIFIED" if status else "ACCESS DENIED"
                time_display = event_time.strftime("%H:%M:%S %d.%m.%Y") if event_time else "NO LOGS"
                reason_display = reason if reason else "No information"

                print(f"| {display_name} | STATUS: {status_display} | TIME: {time_display} | REASON: {reason_display}")
            
            return results
        else:
            print(f"Error: Employee with ID {employee_id} not found or has no logs.")
            return None

    except Exception as e:
        print(f"Error fetching logs: {e}")
        return None
    finally:
        cur.close()
        conn.close()

def get_all_employees():
    """
    Fetches all employees with their ID, name, and verification status.
    """
    conn = get_db_connection()
    if not conn:
        return []

    try:
        cur = conn.cursor()
        # Fetch status from the latest entry in verification_logs for each employee
        cur.execute("""
            SELECT e.qr_hash, e.first_name, e.last_name, vl.status
            FROM employees e
            LEFT JOIN (
                SELECT DISTINCT ON (employee_id) employee_id, status
                FROM verification_logs
                ORDER BY employee_id, event_time DESC
            ) vl ON e.id = vl.employee_id
            ORDER BY e.id DESC;
        """)
        
        rows = cur.fetchall()
        employees = []
        for row in rows:
            employees.append({
                "qr_hash": row[0],
                "first_name": row[1],
                "last_name": row[2],
                "status": "Active" if row[3] else "Inactive" 
            })
            
        return employees
    except Exception as e:
        print(f"Error fetching all employees: {e}")
        return []
    finally:
        if conn:
            conn.close()